language: node_js
node_js:
  - '0.10'
notifications:
  email:
    - evan.huang@xplusz.com
    - tang.jilong@gmail.com
    - kkiiiu@gmail.com
services:
  - mongodb
before_script:
  - npm install -g grunt-cli
after_scipt:
  - grunt doc
branches:
  only:
    - master
deploy:
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: QsRIyY5JLWe8TI4JuWCcuwNqRetAqRZAr5D786zl3mf1uNYZPeffd7AK9iNoT7SlI5sPbJsV9DXnY8vF5D5e/lHbqET18mQWB2bVKb3K79qhze37/wKoRbS7HrL0SgdKKhL+YGprwwdlnfZ9TcuYWi5J4qWpl3it9p0bTIV8uGA=
  app: hearthstone-srv
  strategy: git
  on:
    repo: tim-tang/hearthstone
  run:
    - "mongoose-fixture --fixture=init --remove"
    - "mongoose-fixture --fixture=init --add"
    #- "ps -ef|grep -ie 'mongoose-fixture'|awk '{print $2}' |xargs kill -9"
