language: node_js
node_js:
  - "0.10"
notifications:
  email: 
    - evan.huang@xplusz.com
    - tang.jilong@gmail.com
services:
  - riak 
before_script:
  - "curl http://apt.basho.com/gpg/basho.apt.key | sudo apt-key add -"
  - 'sudo bash -c "echo deb http://apt.basho.com $(lsb_release -sc) main > /etc/apt/sources.list.d/basho.list"'
  - "sudo apt-get update"
  - "yes n | sudo apt-get install riak"
  - "sudo service riak restart"
  - "ulimit -n 2048"
  - "riak version"
  - "cat /etc/riak/app.config"
  - npm install -g grunt-cli
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: c073b681-3e57-41bc-b3e2-8bf270ff80a3 
  app: hearthstone-srv 

