language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
notifications:
  email: 
    - evan.huang@xplusz.com
    - tang.jilong@gmail.com
services:
  - riak 
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: c073b681-3e57-41bc-b3e2-8bf270ff80a3 
  app: hearthstone-srv 
